

POST https://v2.api.noroff.dev/auth/login
Content-Type: application/json

{
    "email": "elilyn00995@stud.noroff.no",
    "password": "lollipop12345"
}


######


POST https://v2.api.noroff.dev/blog/posts/petrine
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicGV0cmluZSIsImVtYWlsIjoiZWxpbHluMDA5OTVAc3R1ZC5ub3JvZmYubm8iLCJpYXQiOjE3MTQ5Mzk5NDR9.yYpWs50Szn6bjn8_xHbEhVaGX42GmA-yIVFz1TilM5U

{
    "title": "Min første blogg post!",
    "body": "Virker dette her i dag da?"
}


########


PUT https://v2.api.noroff.dev/blog/posts/petrine/7187a0af-605b-4cf9-8a01-d7aa37486b18
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicGV0cmluZSIsImVtYWlsIjoiZWxpbHluMDA5OTVAc3R1ZC5ub3JvZmYubm8iLCJpYXQiOjE3MTQ5Mzk5NDR9.yYpWs50Szn6bjn8_xHbEhVaGX42GmA-yIVFz1TilM5U

{
    "body": "Denne posten har blitt redigert!"
}


########


DELETE https://v2.api.noroff.dev/blog/posts/petrine/7187a0af-605b-4cf9-8a01-d7aa37486b18
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicGV0cmluZSIsImVtYWlsIjoiZWxpbHluMDA5OTVAc3R1ZC5ub3JvZmYubm8iLCJpYXQiOjE3MTQ5Mzk5NDR9.yYpWs50Szn6bjn8_xHbEhVaGX42GmA-yIVFz1TilM5U